GSG-G7/lang-mate

- README.md
> make readme file

- README.md
Relates #3
fix readme file to update the user journey
> fix readme file to update the user journey

- README.md
#3
Add tech-stack, team members, database schema and prototype
> Add tech-stack, team members, database schema and prototype

- .travis.yml
- ### The setup for Travis CI
- ### Made the initial test
#8
> Travis Ci 

- client/src/components/commonComponents/Button/index.js
Button component that takes 3 props:
* `text` which is the text to be displayed in the button
* `className` is the css class 
* `onClick` : a function thats invoked when the button is clicked
Relates #41
> button component

- client/src/components/commonComponents/BackButton/index.js
- client/src/components/commonComponents/Button/index.js
back button takes prop: 
* back: which is a function that activates when the user clicks on the button
https://repl.it/@Amoodaa/LimeSelfreliantRectangle
relates #47
> 47 back button

- client/src/App.css
- client/src/components/pages/Login/index.css
- client/src/components/pages/Login/index.js
Create Login page component that contain a welcome greet message and two fields one for username and other for password and button for submit, that's for now and will finish it when the all components are ready to use 
you can import the component in the app file and put it in render to see the changes
> 18 login page

- server/routes/index.js
- Changed the nativeLang route to a better name
> Backend Routes 

- server/app.js
- server/database/config/fakedata.sql
- server/database/queries/interests/getInterests.js
- server/database/queries/messages/addChannel.js
- server/database/queries/messages/getChannelMessages.js
- server/database/queries/users/addUser.js
- server/database/queries/users/changePassword.js
- server/database/queries/users/deactivateUser.js
- server/database/queries/users/getUserChannels.js
- server/database/queries/users/getUserInfo.js
- server/database/queries/users/getUsersByInterest.js
- server/database/queries/users/getUsersByLang.js
- server/database/queries/users/searchUsers.js
added express.json
added a hashed password in fakedata (Fatma123)
fixed value into values
did values again
> Fixes in setup

- server/controllers/auth/authentication.js
- server/helpers/jwtVerifyPromise.js
> 38 auth middleware

- server/controllers/auth/logout.js
- test/routes/index.test.js
- test/routes/logout.test.js
cleared the cookie :sunglasses: 
relates #26
> logout done

- server/controllers/languages/language.js
- test/queries/languages.test.js
#22 
language 'edit to be more clear
> language 'edit to be more clear'

- server/controllers/auth/login.js
- test/routes/index.test.js
- test/routes/login.test.js
added a condition for if there was no user with that username!
relates #28
> added test for login made sure its working

- server/controllers/users/getUsersByLang.js
- server/database/queries/users/getUsersByLang.js
- test/queries/getUsersByLang.test.js
- test/queries/index.test.js
- test/routes/getUsersByLang.test.js
- test/routes/index.test.js
- Wrote the middleware for sending the JSON response of all users
- Wrote the query for getting all users who matches the native language id
- Wrote the tests for both the route and query
**Note**: I used the same format function and maybe I will write this code in a better way when we have time to do so 
Relates: #32
> Users By Native Language

- server/controllers/users/getUsersByInterest.js
used the new format func in the users interest route
#105
> Refactor Users By Interest

- server/controllers/auth/authentication.js
- server/controllers/auth/login.js
- server/controllers/auth/signup.js
- server/controllers/users/changePassword.js
- server/controllers/users/getUsersByInterest.js
- server/controllers/users/searchUsers.js
> rehandled errors accordingly

- server/controllers/auth/login.js
- server/controllers/auth/signup.js
- server/database/queries/users/index.js
- server/database/queries/users/reactivateUser.js
- test/routes/login.test.js
and hes not activated, the server reactivates his acc
and logs him in
needs more testing once the deactivate branch is merged #85 
relates #97
> added that if the user signs 

- client/src/App.js
- client/src/components/pages/Chat/index.js
- client/src/components/pages/Home/index.js
- client/src/components/pages/Landing/index.js
- client/src/components/pages/Login/index.js
- client/src/components/pages/Profile/index.js
- client/src/components/pages/Settings/index.js
- client/src/components/pages/Signup/index.js
- Added all the routes in the react app 
- Added stateless components to handle the routes 
#12
> React Routes 

- server/controllers/auth/authentication.js
- server/controllers/auth/login.js
- server/controllers/auth/signup.js
- server/controllers/users/changePassword.js
- server/controllers/users/getUsersByInterest.js
- server/controllers/users/getUsersByLang.js
- server/controllers/users/searchUsers.js
bc it made problem, and kept going to the next `.then(`
> changed return next to throw next

- server/controllers/users/getUserChannels.js
- server/database/queries/messages/getChaMessagesByChaId.js
- server/database/queries/messages/index.js
- server/database/queries/users/getUserChannels.js
- server/helpers/formatLanguages.js
- server/helpers/formatMessages.js
- server/helpers/index.js
- server/routes/index.js
> 119 channel username

- client/src/App.js
- client/src/components/Auth/PrivateRoute.js
- client/src/components/Auth/auth.js
- client/src/components/pages/Login/index.js
- client/src/services/api.js
- server/controllers/auth/index.js
- server/controllers/auth/isAuth.js
- server/controllers/auth/login.js
- server/routes/index.js
> React Auth

- server/routes/index.js
- test/routes/getInterests.test.js
- test/routes/languages.test.js
see title or commit
relates #127
> got the interests, languages routes before the auth middleware

- server/controllers/users/getUserChannels.js
- server/controllers/users/getUserInfo.js
- server/controllers/users/getUsersByInterest.js
- server/controllers/users/getUsersByLang.js
- server/controllers/users/searchUsers.js
- server/database/queries/users/getUsersByIds.js
- server/database/queries/users/index.js
- server/helpers/formatLanguagesV2.js
- server/helpers/formatUsers.js
- server/helpers/index.js
to send users info who are in any channels of the logged in users
> 129 users channels

- server/controllers/users/getUserChannels.js
- server/helpers/formatMessages.js
> added participants to each channel in the response

- client/src/components/wrapper/WithSubscription.js
- client/src/services/dataSource.js
> 137 single data source
